-- create database syntax
CREATE DATABASE COLLAGE;

-- select DB syntax
USE COLLAGE;

-- create table Syntax
CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL
);

-- add data in table syntax
INSERT INTO STUDENT VALUES(1, "RAJ YADAV", 22);
INSERT INTO STUDENT VALUES(2, "YASHRAJ YADAV", 24);

-- PRINT ALL DATA IN TABLE
SELECT * FROM STUDENT;
