SELECT Name, Marks
FROM STUDENT;

SELECT DISTINCT City
FROM STUDENT;

SELECT City, COUNT(Name)
FROM Student
GROUP BY City;

SELECT City, MAX(Marks)
FROM Student
GROUP BY City;

SELECT mode, COUNT(mode) 
FROM Customer 
GROUP BY mode;

SELECT COUNT(Name) AS Name, MAX(Marks) AS MAX_Marks, City
FROM Student
GROUP BY City
HAVING MAX(Marks) > 90
ORDER BY MAX_Marks DESC;
